# Generated by Django 5.1.2 on 2024-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation_to_ru', models.CharField(default='None', max_length=255)),
                ('guessed', models.PositiveIntegerField()),
                ('wrong', models.PositiveIntegerField()),
                ('archive', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
